version: "3"
services:

  nginx:
    image: 
      ${NGINX_IMAGE_NAME}:${NGINX_IMAGE_VERSION}
    ports:
      - "8989:8989"
    volumes:
      - ${NGINX_CONF_DIR}:C:\nginx\conf
    depends_on:
      - yrunner

  yrunner:
    build: 
      context: .
    image: 
      ${IMAGE_NAME}:${IMAGE_VERSION}
    volumes:
      - ${DATA_DIR}:C:\app\data
      - ${LOG_DIR}:C:\app\logs
    deploy:
      replicas: 1   
    env_file: .env


#
# buiid:  
# docker-compose build
# 
# run: 
# docker run --name api --rm -p 8989:8989 -v data:/app/data --env-file .env -d albert0i/sqlite-server:1.0
#
# EOF (2023/05/29)
#