### runSelectSQL
GET http://localhost:8989/api/v1/yr/runselectsql
Content-Type: application/json
Authorization: Bearer VEUdEii4n7nCvofaBRJEC

{
  "cmdText": "select * from tbrelcod"
}

### runValueSQL
GET http://localhost:8989/api/v1/yr/runvaluesql
Content-Type: application/json
Authorization: Bearer VEUdEii4n7nCvofaBRJEC

{
  "cmdText": "select update_ident from tbrelcod where relcod='99'"
}

### runSQL
POST http://localhost:8989/api/v1/yr/runsql
Content-Type: application/json
Authorization: Bearer VEUdEii4n7nCvofaBRJEC

{
  "cmdTexts": [
      "update tbrelcod set update_ident=update_ident+1 where relcod='99'",
      "update tbrelcod set update_ident=update_ident+1 where relcod='99'",
      "update tbrelcod set update_ident=update_ident+1 where relcod='99'"
      ]
}

### runInsertSQLYieldRowID
POST http://localhost:8989/api/v1/yr/runinsertsqlyieldrowid
Content-Type: application/json
Authorization: Bearer VEUdEii4n7nCvofaBRJEC

{
  "cmdText": "insert into tausers(tunamec, tunamep) values('測試一', 'Test1')",
  "id": "tuid"
}


### RESTful API 

### Get all 
GET http://localhost:8989/api/v1/yr/tbrelcod?orderby=relcod
Content-Type: application/json
Authorization: Bearer VEUdEii4n7nCvofaBRJEC

### Get one

GET http://localhost:8989/api/v1/yr/tbrelcod/99?keyname=relcod&keytype=string
Content-Type: application/json
Authorization: Bearer VEUdEii4n7nCvofaBRJEC

### Create one 
POST http://localhost:8989/api/v1/yr/tbrelcod
Content-Type: application/json
Authorization: Bearer VEUdEii4n7nCvofaBRJEC

{ 
    "relcod" : { "type": "string", "value" : "KK" },
    "reldes" : { "type": "string", "value" : "testing 1" },
    "reldesc" : { "type": "string", "value" : "測試一" },
    "update_ident" : { "type" : "number", "value": 0 }
}

### Update one
PATCH http://localhost:8989/api/v1/yr/tbrelcod/KK?keyname=relcod&keytype=string
Content-Type: application/json
Authorization: Bearer VEUdEii4n7nCvofaBRJEC

{ 
    "reldes" : { "type": "string", "value" : "testing 2" },
    "reldesc" : { "type": "string", "value" : "測試二" },
    "update_ident" : { "type" : "number", "value": 101 }
}

### Delete one 
DELETE http://localhost:8989/api/v1/yr/tbrelcod/KK?keyname=relcod&keytype=string
Content-Type: application/json
Authorization: Bearer VEUdEii4n7nCvofaBRJEC

# 
# REST Client for Visual Studio Code
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
#
